# Generated by Django 2.2.5 on 2019-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191104_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=0),
        ),
    ]
